"""Regenerate results/REPORT.md from the ledger. Claims are written by hand."""

from collections import defaultdict
from pathlib import Path

import numpy as np

from loopgraph import Ledger, Objective, pareto_front
from loopgraph.report import table

R = Path(__file__).resolve().parents[1] / "results"
L = Ledger(R / "ledger.jsonl")

camp = L.entries("distill")
front = sorted(pareto_front(camp, [Objective("success"), Objective("flash_kb", False)]),
               key=lambda e: e.metrics["flash_kb"])
teacher = camp[0].metrics["teacher_success"]
abl = defaultdict(list)
for e in L.entries("dagger_ablation"):
    p = e.params
    abl[(p["width"], p["depth"], p["dagger"])].append(e.metrics["success"])

out = ["# pocketpolicy results", "",
       "Generated by `scripts/report.py` from `ledger.jsonl`. Do not edit by hand.", "",
       f"Teacher (scripted IK expert) success on the 200 held-out episodes: **{teacher:.3f}**.", "",
       "## Pareto frontier: closed-loop success vs flash", "",
       "Success is the int8 policy running the integer pipeline, closed loop, 200 held-out "
       "episodes. Flash is weights plus prep/post constants. The M4 time is derived from the "
       "MAC count (4 cycles/MAC at 168 MHz), not measured.", "",
       table(front, ["width", "depth", "H", "dagger"],
             ["success", "success_float", "flash_kb", "ram_b", "m4_ms_est", "bit_exact"],
             ["width", "depth", "H", "DAgger", "success (int8)", "success (float)", "flash KB",
              "RAM B", "M4 ms (est.)", "bit-exact"]), "",
       f"{len(camp)} runs; proposed by "
       + ", ".join(f"{k} {sum(e.decided_by == k for e in camp)}"
                   for k in sorted({e.decided_by for e in camp})) + ".", "",
       "## DAgger ablation (H=1, 3 seeds each)", "",
       "| width x depth | BC only | DAgger 4 rounds | gain |", "|---|---|---|---|"]
for (w, d) in sorted({(w, d) for w, d, _ in abl}):
    a, b = np.mean(abl[(w, d, 0)]), np.mean(abl[(w, d, 4)])
    out.append(f"| {w} x {d} | {a:.3f} | {b:.3f} | {b - a:+.3f} |")
(R / "REPORT.md").write_text("\n".join(out) + "\n")

print((R / "REPORT.md").read_text())
